files:
  - source: /res/values/strings.xml
    translation: /res/values-%two_letters_code%/strings.xml
  - source: /res/values/shell_strings.xml
    translation: /res/values-%two_letters_code%/shell_strings.xml
